### ISSUE TITLE
Docker compose container wont start

### ISSUE THREAD

**Issue by jasonwragg** [ljmerza/frigate_plate_recognizer#1]
I'm getting the following error. 

frigate_plate_recognizer    | Process Process-1:
frigate_plate_recognizer    | Traceback (most recent call last):
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
frigate_plate_recognizer    |     self.run()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
frigate_plate_recognizer    |     self._target(*self._args, **self._kwargs)
frigate_plate_recognizer    |   File "//./index.py", line 189, in run_mqtt_client
frigate_plate_recognizer    |     client.loop_forever()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
frigate_plate_recognizer    |     rc = self._loop(timeout)
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
frigate_plate_recognizer    |     rc = self.loop_read()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
frigate_plate_recognizer    |     rc = self._packet_read()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
frigate_plate_recognizer    |     rc = self._packet_handle()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
frigate_plate_recognizer    |     return self._handle_publish()
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
frigate_plate_recognizer    |     self._handle_on_message(message)
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
frigate_plate_recognizer    |     on_message(self, self._userdata, message)
frigate_plate_recognizer    |   File "//./index.py", line 108, in on_message
frigate_plate_recognizer    |     response = requests.post(
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 115, in post
frigate_plate_recognizer    |     return request("post", url, data=data, json=json, **kwargs)
frigate_plate_recognizer    |   File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 59, in request
frigate_plate_recognizer    |     return session.request(method=method, url=url, **kwargs)
frigate_plate_recognizer    | TypeError: request() got an unexpected keyword argument 'regions'

frigate:
  frigate_url: http://192.168.1.65:5000
  mqtt_server: 192.168.1.32
  mqtt_auth: false
  mqtt_username: username
  mqtt_password: password
  main_topic: frigate
  camera:
    - front_garden
  min_score: .8
plate_recognizer:
  regions:
    - us-ca
  token: xxx
logger_level: DEBUG

**Comment by ljmerza** [comment]
shoul be fixed in latest version
