### ISSUE TITLE
1.4.1 and 1.5.0 "You can also filter by zones and/or cameras." not working as expected.

### ISSUE THREAD

**Issue by bagobones** [ljmerza/frigate_plate_recognizer#12]
This statement is a bit ambiguous. I initially expected that if BOTH cameras and zones where defined that only events that matched both would be submitted. Like the frigate required_zones feature.

However it appears that if the events matches the zone OR the camera it matches and submits.

Of note zone names are not unique, you could have two different cameras covering the same zone name with different angles.

In my case I have a "driveway" zone with two cameras that can see it, however one is at a bad angle to see the plate so technically I would like to only get that zone WITH a specific camera.

**Comment by bagobones** [comment]
in addition if no cameras are defined and ONLY zones are defined the logs seem to indicate the application is restarting about every minute and doesn't log any events.

**Comment by bagobones** [comment]
Further testing this config in 1.5.0 just restarts on EVERY event

```
frigate:
  frigate_url: http://xxxxxxxxxxx:5000
  mqtt_server: xxxxxxxxxxx
  mqtt_auth: true
  mqtt_username: xxxxxxxxxxx
  mqtt_password: xxxxxxxxxxxxxx
  main_topic: frigate
  return_topic: plate_recognizer
  objects:
    - car
  zones:
    - driveway
    - driveway_entrance
    - garage_entrance
  min_score: .75
plate_recognizer:
  token: xxxxxxxxxxxxxxxxxxxxxx
  regions: 
    - us-ca
logger_level: DEBUG
```

I am seeing the following log repeat every time a car drives by

```
2023-11-15 17:35:00,005 - __main__ - INFO - Frigate Plate Recognizer Version: 1.5.0
2023-11-15 17:35:00,005 - __main__ - DEBUG - config: {'frigate': {'frigate_url': 'http://xxxxxxxxxx:5000', 'mqtt_server': 'xxxxxxx', 'mqtt_auth': True, 'mqtt_username': 'xxxxx', 'mqtt_password': 'xxxxxx', 'main_topic': 'frigate', 'return_topic': 'plate_recognizer', 'objects': ['car'], 'zones': ['driveway', 'driveway_entrance', 'garage_entrance'], 'min_score': 0.75}, 'plate_recognizer': {'token': 'xxxxxxxxxxxxxxx', 'regions': ['us-ca']}, 'logger_level': 'DEBUG'}
2023-11-15 17:35:00,006 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.102.20
2023-11-15 17:35:00,007 - __main__ - INFO - MQTT Connected
```

**Comment by kyle4269** [comment]
Yeah, I noticed the same thing here on my end.. Keeps restarting

**Comment by bagobones** [comment]
> v1.5.1 should fix this

So which way is this fixed?

Can you specify "Zones" with no camera?

If you specify Cameras AND Zones must BOTH match now?

**Comment by ljmerza** [comment]
You should be able to do only zones, only cameras, or both

**Comment by bagobones** [comment]
> You should be able to do only zones, only cameras, or both

If both are specified is it now  an "AND" statement BOTH must match?

**Comment by ljmerza** [comment]
yes

**Comment by bagobones** [comment]
Seems to finally be working as expected.. Now I just have image quality and angle of the car when the snap shot is taken issues .. Might have to upgrade to frigate plus and try out that new plate feature.

**Comment by chrissiesparkle** [comment]
> > You should be able to do only zones, only cameras, or both
> 
> If both are specified is it now an "AND" statement BOTH must match?

Can this be added to the docs? I assumed that it would have been AND/OR rather than just AND...
