### ISSUE TITLE
Frigate Stream integration

### ISSUE THREAD

**Issue by gadget-man** [ljmerza/frigate_plate_recognizer#18]
This looks amazing, but I'd like to be able to use it with Frigate stream rather than Snapshot. Is this possible?

**Comment by ljmerza** [comment]
I dont think there's a way to add text to a stream in frigate via api

**Comment by kyle4269** [comment]
I did ask Nick about this a while ago. He said it's something they talked about, but isn't high on the list.

**Comment by gadget-man** [comment]
Noted. Will close this request.
