### ISSUE TITLE
Help retrieve picture/data

### ISSUE THREAD

**Issue by Ostedtinkerer** [ljmerza/frigate_plate_recognizer#23]
Hello

And thanks for the help with the config issue. All is up and running now, and is working fine.

How do i retrieve the data from mqtt? - frigate sublabel.
I can see this container stores it in .db. and i can see it in the logs.

but i dont have anything in frigate or homeassistant.

I could be looking the wrong places, or missing a sensor in ha.

**Comment by kyle4269** [comment]
You're welcome! If it was successful, under events in frigate you should see "Car: plate#".

**Comment by Ostedtinkerer** [comment]
ahh. That makes sense, i found it. Thanks again.
