### ISSUE TITLE
FR: Arm version for Raspberry Pi

### ISSUE THREAD

**Issue by conorlap** [ljmerza/frigate_plate_recognizer#3]
Would be great if this worked on Raspberry Pi!

Thanks for your efforts!

**Comment by ljmerza** [comment]
i dont ahve a raspbeeri pi to test but what is making this not work on one? Its a simple python script so should work

**Comment by conorlap** [comment]
I think just adding **#!/bin/python3** to the top of the index.py file would work actually!

**Comment by ljmerza** [comment]
added
