### ISSUE TITLE
How to use YOLOv8

### ISSUE THREAD

**Issue by DrSpaldo** [ljmerza/frigate_plate_recognizer#33]
I was wondering if there was a way to make Frigate Plate Recognizer use YOLOv8 in CodeProject.AI ?

**Comment by ljmerza** [comment]
this looks to be a codeproject.ai question

**Comment by DrSpaldo** [comment]
> this looks to be a codeproject.ai question

Nice “answer”

**Comment by ljmerza** [comment]
I think this is a code project.ai setting that once you set, it will just work. I haven't used code project.ai much but looks like you need to install the module for yolov8 and enable.
