### ISSUE TITLE
Is there a way to use this in automations in Home Assistant?

### ISSUE THREAD

**Issue by Heisenberg2980** [ljmerza/frigate_plate_recognizer#4]
Is there a way for Home Assistant to know this process has been executed and what plates have been detected to use this information in automations?  (i.e. notify you when a known/unkown car has been detected)

**Comment by ljmerza** [comment]
in v1.3.0 I added a return topic config `return_topic: plate_recognizer` that returns a mqtt message with plate data

**Comment by Heisenberg2980** [comment]
@ljmerza you are a star! testing it now

**Comment by Heisenberg2980** [comment]
The process generates this error and restarts when trying to write a message to the return topic:

```TypeError: payload must be a string, bytearray, int, float or None.```

**Comment by heisenberg2980** [comment]
Error has been fixed in 1.3.2, thanks @ljmerza 

Note: For anyone coming here with a similar question, Plate Recognizer also has a Webhooks option (included in the free account) that can be setup to call Home Assistant every time a call to the recognition API is made.

**Comment by BliXem1** [comment]
Alright, this is the first time for me, I set this ip, did the config and MQTT within Frigate and the frigate_plate_rec.

```
2024-02-09 00:00:12,316 - __main__ - INFO - Frigate Plate Recognizer Version: 1.8.8
2024-02-09 00:00:12,316 - __main__ - INFO - Using CodeProject.AI API
2024-02-09 00:00:12,316 - __main__ - INFO - Starting MQTT client. Connecting to: 192.168.0.125
2024-02-09 00:00:12,317 - __main__ - INFO - MQTT Connected
```

MQTT has been setup within Home Assistant, it's connected with Frigate and the plate_rec. But where can I find this? The notification for when a known/unkown car has been detected.
This is for my garage, when it reconize the license plate the garagedoor opens. Where can I add the license plate btw so it knows i'm on the driveway?

**Comment by ljmerza** [comment]
The docs mention an mqtt event that will be sent when a license plate is detected. You can use that to create an entity from the mqtt sensor entity

**Comment by BliXem1** [comment]
Maybe @heisenberg2980 want to share his MQTT configuration? It's important for me that if it detects my license plate the garagedoor opens.

**Comment by heisenberg2980** [comment]
@BliXem1 I am using the webhook option I mentioned here: https://github.com/ljmerza/frigate_plate_recognizer/issues/4#issuecomment-1714566767 but getting the value from MQTT shouldn´t be difficult. If this is the first time you are working with MQTT, I would recommend you to install the Windows app "MQTT Explorer" as a first step, so you can see if the messages from plate recognizer are reaching your MQTT broker
