### ISSUE TITLE
Possible bug and right way to setup Mqtt sensor?

### ISSUE THREAD

**Issue by atv2016** [ljmerza/frigate_plate_recognizer#41]
Have a few events now where there is a car but I guess it's not recognising the plate properly and instead reads the text of the camera instead (CAM01 etc) and puts that in as a sub label.

I guess I could remove the camera name or even mask it out in frigate, but maybe there is a better way to combat this ?

Also for Mqtt, I guess the best way is to do it like below? Is there a way to also read out watched plates ?

  - name: "License plate"
    state_topic: "frigate/platerecognizer"
    value_template: ""
    unit_of_measurement: "na"
    json_attributes_topic: "na"
    icon: mdi:car
    # Below lines only needed if long term statistics are required
    state_class: "measurement"

**Comment by ljmerza** [comment]
hey this is probably best asked in the home assistant forums on how to create an mqtt sensor from a mqtt event

**Comment by atv2016** [comment]
Hmm this is not really about that more about how I utilise the watched plates? I don't see it in the MQTT topic, I just see this:

 / 



{
  "plate_number": "CAM03",
  "score": 0.899,
  "frigate_event_id": "1709120379.716305-p9qjp3",
  "plate_number": "VI6CZA",
  "score": 0.89,
  "frigate_event_id": "1709048777.461169-e4ygo1",
  "camera_name": "front_driveway_1",
  "start_time": "2024-02-28 11:39:39"
  "start_time": "2024-02-27 15:46:17"
}

**Comment by kyle4269** [comment]
> Hmm this is not really about that more about how I utilise the watched plates? I don't see it in the MQTT topic, I just see this:
> 
> 
> 
> {
> 
>   "plate_number": "CAM03",
> 
>   "score": 0.899,
> 
>   "frigate_event_id": "1709120379.716305-p9qjp3",
> 
>   "plate_number": "VI6CZA",
> 
>   "score": 0.89,
> 
>   "frigate_event_id": "1709048777.461169-e4ygo1",
> 
>   "camera_name": "front_driveway_1",
> 
>   "start_time": "2024-02-28 11:39:39"
> 
>   "start_time": "2024-02-27 15:46:17"
> 
> }
> 
> 
> 
> Would it get added to this if it matched as per the comment on the front page? 
> 
> 
> 
> > The original plate will be added to the MQTT response as an additional original_plate field.

That's correct.  If there is a match, you'll see the plate_number and original_plate in the mqtt payload..

**Comment by atv2016** [comment]
Nice one, thanks!
