### ISSUE TITLE
Registered plates homeassistant

### ISSUE THREAD

**Issue by Ostedtinkerer** [ljmerza/frigate_plate_recognizer#45]
What is the workaround to list the registered plates in homeassistant?
Is there already a solution? - i cant seem to find it anywhere. Tried several things with ha/mqtt.

Btw this project works very good!

**Comment by atv2016** [comment]
What workaround are you referring to ?

**Comment by Ostedtinkerer** [comment]
Maybe wrong typing sorry. 
I ment how can i list the plates registered here, to show in homeassistant? 
By the frigate integration. I can clearly see the plates registered in frigate sublabels, but they dont seem to come into homeassistant. Or i dont know what i am missing.

**Comment by atv2016** [comment]
This only works with a container btw (afaik). But assuming you have a MQTT broker setup (e.g. Mosquito) you just put in a MQTT sensor in wherever you have your yaml files (configuration.yaml or split up e.g. mqtt.yaml) and add:

 sensor:

# Platerecognizer MQTT topic
  - name: "License plate"
    state_topic: "frigate/plate_recognizer"
    value_template: "{{ value_json.plate_number }}"
    #unit_of_measurement: "na"
    json_attributes_topic: "frigate/plate_recognizer"
    icon: mdi:car

That should give you everything you need.

**Comment by chrissiesparkle** [comment]
> This only works with a container btw (afaik). But assuming you have a MQTT broker setup (e.g. Mosquito) you just put in a MQTT sensor in wherever you have your yaml files (configuration.yaml or split up e.g. mqtt.yaml) and add:
> 
> ```
>  sensor:
> # Platerecognizer MQTT topic
>   - name: "License plate"
>     state_topic: "frigate/plate_recognizer"
>     value_template: "{{ value_json.plate_number }}"
>     #unit_of_measurement: "na"
>     json_attributes_topic: "frigate/plate_recognizer"
>     icon: mdi:car
> ```
> 
> That should give you everything you need.

This is a really good post. Hopefully someone can add it to the docs

**Comment by federicotravaini** [comment]
> > This only works with a container btw (afaik). But assuming you have a MQTT broker setup (e.g. Mosquito) you just put in a MQTT sensor in wherever you have your yaml files (configuration.yaml or split up e.g. mqtt.yaml) and add:
> > ```
> >  sensor:
> > # Platerecognizer MQTT topic
> >   - name: "License plate"
> >     state_topic: "frigate/plate_recognizer"
> >     value_template: "{{ value_json.plate_number }}"
> >     #unit_of_measurement: "na"
> >     json_attributes_topic: "frigate/plate_recognizer"
> >     icon: mdi:car
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That should give you everything you need.
> 
> This is a really good post. Hopefully someone can add it to the docs

THIS should be in the documentation!
